//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_ADS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_PostJob
    {
        public int ID { get; set; }
        public string JOB_Title { get; set; }
        public string JOB_Location { get; set; }
        public string JOB_Region { get; set; }
        public string JOB_Type { get; set; }
        public string JOB_Description { get; set; }
        public string JOB_Requirement { get; set; }
        public string Option_Chevron { get; set; }
        public string Option_Adisorn { get; set; }
        public string OPtion_Others { get; set; }
        public string Company_Name { get; set; }
        public string Featured_Image { get; set; }
        public string Logo_Image { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> JOB_CreateDate { get; set; }
        public Nullable<System.DateTime> JOB_UpdateDate { get; set; }
        public string Status { get; set; }
        public string Experience { get; set; }
        public string Salary { get; set; }
        public string Gender { get; set; }
    }
}
