//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_ADS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_Master_Department
    {
        public int ID { get; set; }
        public string Department_Code { get; set; }
        public string Department_Name { get; set; }
        public string Department_Des { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Status { get; set; }
    }
}
