//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_ADS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_Register
    {
        public int ID { get; set; }
        public string Job_Seekers { get; set; }
        public string Re_Title_EN { get; set; }
        public string Re_Name_EN { get; set; }
        public string Re_Surname_EN { get; set; }
        public string Re_Title_TH { get; set; }
        public string Re_Name_TH { get; set; }
        public string Re_Surname_TH { get; set; }
        public string Re_Phone { get; set; }
        public string Re_Email { get; set; }
        public string Re_Current_Position { get; set; }
        public string Re_Department { get; set; }
        public string Re_Position { get; set; }
        public string Status { get; set; }
        public string Status_Appointment { get; set; }
        public string Status_Confirm { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public Nullable<System.DateTime> Confirm_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string BirthDays { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string VC_File { get; set; }
        public string Pic_File { get; set; }
        public string Cer_File { get; set; }
        public string Check { get; set; }
        public string Em_Code { get; set; }
        public string Exp { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public string CerWork_File { get; set; }
    }
}
