//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_ADS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_Candidate
    {
        public int ID { get; set; }
        public Nullable<int> Re_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string UserApp { get; set; }
        public string Detail { get; set; }
    }
}
